### PR TITLE
Less restrictive dtmin

### PR DESCRIPTION
**Pull request by YingboMa**
Needs https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/441

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
We should similarly do StochasticDiffEq and make sure DelayDiffEq is good with this.

**Comment by ChrisRackauckas** [comment]
Some dispatches are missing: https://travis-ci.org/JuliaDiffEq/OrdinaryDiffEq.jl/jobs/653226807#L766

**Comment by YingboMa** [comment]
https://travis-ci.org/JuliaDiffEq/OrdinaryDiffEq.jl/jobs/653272862#L878
broken test due to StaticArrays.jl's behavior change.
```julia
julia> (@SMatrix [1 2; 3 4]) * ones(2)
2-element SArray{Tuple{2},Float64,1,2} with indices SOneTo(2):
 3.0
 7.0
```

**Comment by ChrisRackauckas** [comment]
The new dtmin doesn't seem to respect units 🤷‍♂

**Pull request merged**
