### PR TITLE
Singular MM's initialization

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
Fixes https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/1039
Fixes https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/1042

@YingboMa can you add the singular mass-matrix initialization?

@kanav99 what should we do about `du`? Re-compute it on demand when we reinitialize?

P.S. need a doc update that describes the intializealgs

### CODE REVIEW

**Comment by kanav99** [comment]
When all could the user ask for `du`? inside callbacks I guess and after each `step!` - any other case? In full initialization, `du` will always be set automatically. Otherwise in most BDFs, we have a linear formula of `du` we can have a separate function for each BDF. Note that `du` is never used internally and is not important for the algorithm to work.

**Comment by ChrisRackauckas** [comment]
I guess it only shows up in initialize, but with this method we need a `du` to reinitialize after a callback, so we somehow have to pick one.

**Comment by ChrisRackauckas** [comment]
I added initialization for singular mass matrices, but it assumes semi-explicit form.

**Comment by ChrisRackauckas** [comment]
Open an issue on semi-explicit form in DAE initialization

**Comment by ChrisRackauckas** [comment]
Open an issue on tolerances of DAE initialization

**Comment by ChrisRackauckas** [comment]
Talking with Yingbo, I realized that things that commonly use a non semiexplicit form are index 2, since they are relating differential variables to differential variables as a constraint. Seems like an issue to punt for now.

**Comment by kanav99** [comment]
> Open an issue on semi-explicit form in DAE initialization
We don't have a problem form for Semi Explicit DAEs. Can I work on it next?

**Comment by dkarrasch** [comment]
This PR made the following problem fail, because it now calls `lu` on a `Diagonal`, which is not defined in `LinearAlgebra`:
```julia
using OrdinaryDiffEq, DiffEqDevTools, SparseArrays, LinearAlgebra

u0 = sin.(range(0, pi, length = 100))
tspan = (0.0, 1.0)

M = 0.5Diagonal(ones(100))
A = spdiagm(0 => ones(100))
update_func = (_A, u, p, t) -> _A.nzval .= t
f = DiffEqArrayOperator(A; update_func=update_func)

prob = ODEProblem(ODEFunction(f; mass_matrix=M), u0, tspan)
solve(prob, ImplicitEuler(linsolve=LinSolveFactorize(lu)))
```
gives
```julia
ERROR: MethodError: no method matching lu!(::Diagonal{Float64,Array{Float64,1}}, ::Val{true}; check=false)
```
Should there be specializations of `issingular` for structured matrices? Or maybe some keyword option, that allows to set `issingular` to `true`, but does an `lu` check by default?

**Comment by ChrisRackauckas** [comment]
>Should there be specializations of issingular for structured matrices? Or maybe some keyword option, that allows to set issingular to true, but does an lu check by default?

Yes, we should specialize this on operator types and matrices.

**Comment by ChrisRackauckas** [comment]
Sorry if this is taking awhile, but I want to make sure we do this right. I'm taking this all the way to ArrayInterface to make `issingular` a thing: https://github.com/JuliaDiffEq/ArrayInterface.jl/pull/42 and then we'll just be using that.

**Pull request merged**
