### PR TITLE
Refactor Gitlab CI

### PR DESCRIPTION
**Pull request by devmotion**
This is an alternative to https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/898 which seemed to work during my experiments and uses the same shell runner as before.

### CODE REVIEW

**Comment by devmotion** [comment]
With this PR Gitlab CI runs the extrapolation tests as well. However, the [logs](https://gitlab.com/juliadiffeq/OrdinaryDiffEq-jl/-/jobs/279393606) show that currently 3 out of 10 tests of ImplicitEulerExtrapolation are broken. Is this known and will this be fixed by https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/892?

**Comment by ChrisRackauckas** [comment]
Yes, the issue was the other CI didn't catch the thread-safety issues.

**Comment by devmotion** [comment]
Good to merge then?

**Comment by devmotion** [comment]
The spurious QNDF1 convergence errors show up again but are clearly unrelated.

**Pull request merged**
