### PR TITLE
[ci skip] Benchmark

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
@DiffEqBot runbenchmarks

### CODE REVIEW

**Comment by kanav99** [comment]
@DiffEqBot runbenchmarks

**Comment by kanav99** [comment]
DiffEqBot doesn't run on descriptions.

**Comment by devmotion** [comment]
On master TRBDF2 also shows regressions compared with June 😞

**Comment by ChrisRackauckas** [comment]
@yingboma I think mentioned a few things about how some of the Jacobian reuse improvements hurt small matrix benchmarks, and this must be hitting that. At least it looks like it's not this PR. We need to really take another look at that whole reuse logic anyways.

**Pull request closed without merging**
