### PR TITLE
`MArray` compatibility

### PR DESCRIPTION
**Pull request by YingboMa**
There is
```julia
    f₀ = zero.(u0./t)
    u0 isa MArray && (f₀ = MArray(f₀))
```
because broadcasting an `MArray` results an `SArray`.
```julia
julia> ode.u0
2-element MArray{Tuple{2},Float64,1,2}:
 1.0
 2.0

julia> ode.u0 ./ 1
2-element SArray{Tuple{2},Float64,1,2}:
 1.0
 2.0
```

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
looks like SArray tests fail here?

**Comment by YingboMa** [comment]
`eltype(m)` can be an `MArray`, too. https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/test/static_array_tests.jl#L4

**Comment by ChrisRackauckas** [comment]
`recursive_bottom_eltype(m)`.

**Comment by YingboMa** [comment]
That doesn't seem to work either...
```julia
julia> u0 = fill(zero(MVector{2,Float64}), 2); t = 0.1;

julia> similar(u0)
2-element Array{MArray{Tuple{2},Float64,1,2},1}:
 #undef
 #undef

julia> similar(u0, eltype(eltype(u0)))
2-element Array{Float64,1}:
 6.9502444917253e-310
 6.9502444933561e-310

julia> similar(u0, typeof(oneunit(eltype(eltype(u0)))/oneunit(t)))
2-element Array{Float64,1}:
 6.9501798101687e-310
 6.9501798097537e-310
```

**Comment by ChrisRackauckas** [comment]
This fix is really sketch and fails tests.

**Comment by YingboMa** [comment]
In favor of https://github.com/JuliaArrays/StaticArrays.jl/pull/536

**Pull request closed without merging**
