### PR TITLE
Call @ode_exit_conditions in step!

### LINKED ISSUE #318: @ode_exit_conditions
`step!` is now

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/79a2e1478263f5f030eafdcb2cf1ea4eb40d5b05/src/iterator_interface.jl#L1-L19

and `solve!` is

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/79a2e1478263f5f030eafdcb2cf1ea4eb40d5b05/src/solve.jl#L334-L347

Should we call `@ode_exit_conditions` (or `check_error!`) before `perform_step!` in `step!` as well?

It's somewhat related to what @devmotion was mentioning in https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/316#issuecomment-381069870

### PR DESCRIPTION
**Pull request by tkf**
closes #318

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Should do the same for stochastic?

**Comment by ChrisRackauckas** [comment]
Why not just use `check_error!(integrator) != :Success` inside `step!` directly?

**Comment by tkf** [comment]
Yes. That's much better. Fixed.

**Comment by ChrisRackauckas** [comment]
Merge when tests pass.

**Pull request merged**
