### PR TITLE
Upper bound DiffEqBase and ExponentialUtilities

### PR DESCRIPTION
**Pull request by devmotion**
Add semver compatible upper bounds for DiffEqBase and ExponentialUtilities (see https://julialang.github.io/Pkg.jl/v1/compatibility/#Version-specifier-format-1).

Should we do the same even for dependencies with 0.x version numbers? And should we update the registry for old releases?

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Past versions need the upper bound too. @stefankarpinski what's the right way to do that with the new registry setup?

**Comment by StefanKarpinski** [comment]
Make a PR to the registry editing the Compat.toml files there by hand.

**Comment by devmotion** [comment]
Should we also drop support for old versions of StaticArrays and DataStructures?

**Comment by ChrisRackauckas** [comment]
I think so. At whatever point they put the 1.0 we should go with that, but until then we just stay up to date.

**Comment by devmotion** [comment]
@ChrisRackauckas Good to merge now?

**Comment by ChrisRackauckas** [comment]
Yes, but without editing the Compat.toml we cannot tag.

**Pull request merged**
