### PR TITLE
Fix performance regression

### PR DESCRIPTION
**Pull request by YingboMa**
Fixes https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/571

```julia
julia> @btime solve($probs,$(Tsit5())); # master
  2.981 ms (60568 allocations: 4.10 MiB)

julia> @btime solve($probs,$(Tsit5())); # PR
  487.315 μs (2664 allocations: 473.02 KiB)
```

### CODE REVIEW

**Comment by devmotion** [comment]
I guess the implementation of `calculate_residuals(u₀, u₁, α, ρ, internalnorm)` in lines 114 to 116 is affected by the same problem, isn't it?

**Comment by dkarrasch** [comment]
What types of `internalnorm` can be used? I thought one could, for instance, define an `internalnorm` that computes the norm based on only few of the components. That couldn't be called on numbers then?

**Comment by devmotion** [comment]
At the moment you have to define a scalar norm as well but that will be changed in the next DiffEq release. There's a discussion about this issue in https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/569.

**Comment by YingboMa** [comment]
> By the way, did you test whether the different implementations are still required?

Yes, it is still needed.

**Comment by ChrisRackauckas** [comment]
Sweet, I find this to be cleaner as well.

**Comment by dkarrasch** [comment]
Can we please get a version tag for this fix? Or are there more things currently in the pipeline?

**Comment by ChrisRackauckas** [comment]
Release made

**Pull request merged**
