### PR TITLE
[ci skip] benchmark

### PR DESCRIPTION
**Pull request by kanav99**

### CODE REVIEW

**Comment by kanav99** [comment]
@DiffEqBot runbenchmarks

**Comment by ChrisRackauckas** [comment]
This looks good, though I would make one change. I would get rid of lsoda from Pollu, and keep a comment in there that it is because it's too slow and messes with the scaling of the plot.

**Comment by devmotion** [comment]
Was this intended to be merged at all? I thought this PR was just opened for running the benchmarks.

**Comment by ChrisRackauckas** [comment]
Oops, I thought this was the same one that changed the benchmark methods. Anyways, it's not a big deal this merged.

**Pull request merged**
