### PR TITLE
Document `savevalues!` and make it return booleans

### PR DESCRIPTION
**Pull request by YingboMa**
Per the discussion in https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/514#issuecomment-426416101.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
If we're going to do this then every `saveat` should act the same.

**Comment by MSeeker1340** [comment]
For some strange reason PuMaS errors on this branch:

```
SS=2 and Overlap Tests: Error During Test at /home/mseeker/.julia/dev/PuMaS/test/runtests.jl:12
  Got exception outside of a @test
  LoadError: BoundsError: attempt to access false
    at index [2]
  Stacktrace:
   [1] indexed_iterate(::Bool, ::Int64, ::Nothing) at ./tuple.jl:69
   [2] apply_discrete_callback! at /home/mseeker/.julia/dev/OrdinaryDiffEq/src/callbacks.jl:248 [inlined]
```

The stack trace is really cryptic... I might need to consult a debugger for this.

**Comment by MSeeker1340** [comment]
OK now. So the mismatch of lhs arguments results in the `BoundsError`... I'll keep this in mind ;)

I think Python did a better job at indicating errors in argument unpacking:

```python
>>> a, b, c = 1, 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by ChrisRackauckas** [comment]
Docstrings should get added here: https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/integrator_interface.jl

**Pull request closed without merging**
