### PR TITLE
Use DiffEqBase.check_error!

### PR DESCRIPTION
**Pull request by tkf**
https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/276

### CODE REVIEW

**Comment by devmotion** [comment]
Is `@ode_exit_conditions` only used inside of `solve!` in OrdinaryDiffEq and DelayDiffEq? Since it consists only of one line anymore we could remove it completely, I guess.

**Comment by ChrisRackauckas** [comment]
Yeah, we just need to make sure we handle the returns. It's a macro because if it's a function then it won't fully return out of `solve!`.

**Comment by ChrisRackauckas** [comment]
Should restart after https://github.com/JuliaLang/METADATA.jl/pull/14250

**Comment by ChrisRackauckas** [comment]
Test failure is some Rosenbrock thing where Travis doesn't finish them sometimes which I don't understand...

**Pull request merged**
