### PR TITLE
Fix creation of rate vector for array partitions

### PR DESCRIPTION
**Pull request by devmotion**
Enables creation of heterogeneous rate vectors. See https://github.com/JuliaDiffEq/RecursiveArrayTools.jl/pull/18.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
This should get a lower bound for the next RecursiveArrayTools

**Comment by ChrisRackauckas** [comment]
waiting on https://github.com/JuliaLang/METADATA.jl/pull/10746 to test and merge.

**Comment by ChrisRackauckas** [comment]
Test failures

**Comment by devmotion** [comment]
Thanks for already fixing that stupid error I introduced!

**Comment by devmotion** [comment]
Still needs https://github.com/JuliaLang/METADATA.jl/pull/10775, but at least mass matrix tests pass now.

**Pull request merged**
