### PR TITLE
Implemented RKM from Mead, Renaut (1999) 

### PR DESCRIPTION
**Pull request by keshavseksaria**
Implemented RKM from [Mead, Renaut (1999)](https://ac.els-cdn.com/S0021999199962605/1-s2.0-S0021999199962605-main.pdf?_tid=477a9208-ac98-49cb-9e33-708859fd93e4&acdnat=1548187474_af02cb708593c8dd3bdb7067ff57bdbb) #493

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Convergence tests are failing.

**Comment by ranocha** [comment]
I don't want to play the devil's advocate, but it might be confusing if this method is implemented in `ssprk_*.jl` because it is not SSP.

**Comment by utkarsh530** [comment]
@ChrisRackauckas can I work on this PR?

**Comment by ChrisRackauckas** [comment]
Yes, it'll be nice to have it finished. But after this you'll want to move to a more difficult method.

**Comment by ChrisRackauckas** [comment]
Supersceded by https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/1052

**Pull request closed without merging**
