### PR TITLE
Add documentation string to ODEIntegrator

### PR DESCRIPTION
**Pull request by Datseris**
This is important for DynamicalSystems.jl due to how I create the docs! :)

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
It's weird to just have partial docs here though. Why not just point to the page, or put the whole thing there? It's weirdly in the middle.

**Comment by Datseris** [comment]
Okay. Can we at least leave `step!(integrator)` and the paragrah that shows the relevant fields there?

Simply for interactiveness purposes.

**Comment by ChrisRackauckas** [comment]
Sure, a relatively short form is fine.

**Comment by Datseris** [comment]
Okay, check if the string is fine, I thing it is quite minimal but still very helpful.

**Pull request merged**
