### PR TITLE
Add warning message when ImplicitEuler or Trapezoid is used without saving

### PR DESCRIPTION
**Pull request by YingboMa**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
why don't we just fix the error estimator? These are really just useful in PDEs where we expect save_everystep=false

**Comment by ChrisRackauckas** [comment]
Wait, why is this an issue? Aren't they used cached values for previous points?

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/perform_step/sdirk_perform_step.jl#L296

**Comment by YingboMa** [comment]
`uprev2` is from `integrator` https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/perform_step/sdirk_perform_step.jl#L282, is that going to be an issue?

**Comment by ChrisRackauckas** [comment]
That doesn't use `sol`. It's a thing that's handled like FSAL as part of the integrator, and only when `alg_extrapolates` is true.

**Comment by YingboMa** [comment]
I see.

**Pull request closed without merging**
