### PR TITLE
Step-by-step refactoring of nonlinear solvers

### PR DESCRIPTION
**Pull request by devmotion**
This PR refactors the nonlinear solvers and the derivative handling in OrdinaryDiffEq in a sequence of commits. Purposefully, this PR does not fix any of the existing bugs both in the implementation of the nonlinear solvers nor in the derivative handling, which are among others
- incorrect handling of failed convergence of the nonlinear solvers, possibly leading to incorrectly accepted steps,
- incorrect handling of linear problems such as inconsistent checks for linearity,
- inconsistencies between in-place and out-of-place algorithms.
IMO these should be fixed in separate PRs, to be able to spot possible performance regressions more easily.

The only intended algorithm change is the removal of the updates of the residuals in the Anderson acceleration (see https://github.com/JuliaDiffEq/DiffEqBase.jl/issues/310). Intuitively, it seems more reasonable to compare the residuals `g(z) - z` in subsequent iterations, as in the regular functional iteration, instead of the residuals `z - zprev`, where `z` is the update of `g(zprev)` by Anderson acceleration.

For each commit, all OrdinaryDiffEq tests (should) pass and the output of
```julia
using OrdinaryDiffEq, Test, ParameterizedFunctions

d_alembert = @ode_def DAlembert begin
    dx = a - b*x + c*t
end a b c
function d_alembert_analytic(u0,p,t::Number)
    a,b,c = p
    ebt = exp(b*t)
    @. exp(-b*t)*(-a*b + c + ebt*(a*b + c*(b*t - 1)) + b^2 * u0)/(b^2)
end

p = (1., 2., 3.)
u0 = [1.0]
tspan = (0.0,10.0)
prob = ODEProblem(ODEFunction(d_alembert.f,
                              jac = d_alembert.jac,
                              analytic=d_alembert_analytic),
                              u0,tspan,p)

println("Rosenbrock23")
sol = solve(prob,Rosenbrock23(),abstol=1e-8,reltol=1e-8)
@show sol.destats
@show sol.errors
@test sol.errors[:l2] < 1e-7

println("Rodas4")
sol = solve(prob,Rodas4(),abstol=1e-10,reltol=1e-10)
@show sol.destats
@show sol.errors
@test sol.errors[:l2] < 1e-7

println("Veldd4")
sol = solve(prob,Veldd4(),abstol=1e-10,reltol=1e-10)
@show sol.destats
@show sol.errors
@test sol.errors[:l2] < 1e-7

println("Rodas5")
sol = solve(prob,Rodas5(),abstol=1e-10,reltol=1e-10)
@show sol.destats
@show sol.errors
@test sol.errors[:l2] < 1e-7

println("Trapezoid")
sol = solve(prob,Trapezoid(),abstol=1e-10,reltol=1e-10)
@show sol.destats
@show sol.errors
@test sol.errors[:l2] < 2e-6

println("KenCarp3")
sol = solve(prob,KenCarp3(),abstol=1e-10,reltol=1e-10)
@show sol.destats
@show sol.errors
@test sol.errors[:l2] < 8e-4

println("KenCarp4")
sol = solve(prob,KenCarp4(),abstol=1e-10,reltol=1e-10)
@show sol.destats
@show sol.errors
@test sol.errors[:l2] < 1e-7

println("KenCarp4 - Functional")
sol = solve(prob,KenCarp4(nlsolve=NLFunctional()),abstol=1e-10,reltol=1e-10)
@show sol.errors

println("TRBDF2 - Functional")
sol = solve(prob,TRBDF2(nlsolve=NLFunctional()),abstol=1e-10,reltol=1e-10)
@show sol.errors

println("TRBDF2")
sol = solve(prob,TRBDF2(),abstol=1e-10,reltol=1e-10)
@show sol.destats
@show sol.errors
@test sol.errors[:l2] < 2e-6
```
and
```julia
using OrdinaryDiffEq, Test, LinearAlgebra, Statistics

@testset "Mass Matrix Accuracy Tests" begin

  # create mass matrix problems
  function make_mm_probs(mm_A, ::Val{iip}) where iip
    # iip
    mm_b = vec(sum(mm_A; dims=2))
    function mm_f(du,u,p,t)
      mul!(du,mm_A,u)
      du .+= t * mm_b
      nothing
    end
    mm_g(du,u,p,t) = (@. du = u + t; nothing)

    # oop
    mm_f(u,p,t) = mm_A * (u .+ t)
    mm_g(u,p,t) = u .+ t

    mm_analytic(u0, p, t) = @. 2 * u0 * exp(t) - t - 1

    u0 = ones(3)
    tspan = (0.0, 1.0)

    prob = ODEProblem(ODEFunction{iip,true}(mm_f, analytic=mm_analytic, mass_matrix=mm_A), u0, tspan)
    prob2 = ODEProblem(ODEFunction{iip,true}(mm_g, analytic=mm_analytic), u0, tspan)

    prob, prob2
  end

  function _norm_dsol(alg,prob,prob2)
    sol = solve(prob,  alg,dt=1/10,adaptive=false)
    sol2 = solve(prob2,alg,dt=1/10,adaptive=false)
    norm(sol .- sol2)
  end

  # test functional iteration
  for iip in (false, true)
    prob, prob2 = make_mm_probs(Matrix{Float64}(1.01I, 3, 3), Val(iip))

    sol = solve(prob,ImplicitEuler(
                          nlsolve=NLFunctional()),dt=1/10,adaptive=false,reltol=1e-7,abstol=1e-10)
    sol2 = solve(prob2,ImplicitEuler(nlsolve=NLFunctional()),dt=1/10,adaptive=false,reltol=1e-7,abstol=1e-10)
    @show sol.errors
    @show sol2.errors
    @test norm(sol .- sol2) ≈ 0 atol=1e-7

    sol = solve(prob, ImplicitMidpoint(extrapolant = :constant,
                          nlsolve=NLFunctional()),dt=1/10,reltol=1e-7,abstol=1e-10)
    sol2 = solve(prob2,ImplicitMidpoint(extrapolant = :constant, nlsolve=NLFunctional()),dt=1/10,reltol=1e-7,abstol=1e-10)
    @show sol.errors
    @show sol2.errors
    @test norm(sol .- sol2) ≈ 0 atol=1e-7

    sol = solve(prob,ImplicitEuler(nlsolve=NLAnderson()),dt=1/10,adaptive=false)
    sol2 = solve(prob2,ImplicitEuler(nlsolve=NLAnderson()),dt=1/10,adaptive=false)
    @show sol.errors
    @show sol2.errors
    @test norm(sol .- sol2) ≈ 0 atol=1e-7
    @test norm(sol[end] .- sol2[end]) ≈ 0 atol=1e-7

    sol = solve(prob, ImplicitMidpoint(extrapolant = :constant, nlsolve=NLAnderson()),dt=1/10,reltol=1e-7,abstol=1e-10)
    sol2 = solve(prob2,ImplicitMidpoint(extrapolant = :constant, nlsolve=NLAnderson()),dt=1/10,reltol=1e-7,abstol=1e-10)
    @test norm(sol .- sol2) ≈ 0 atol=1e-7
    @test norm(sol[end] .- sol2[end]) ≈ 0 atol=1e-7
  end
end
```
should be identical.

We might want to add additional fields to the out-of-place version of the Newton solvers such as `new_W`, rename `ztmp` to something more meaningful such as `znext` (actually, caching the next iterate and using `apply_step!` could/should be removed completely - however, since `nlsolvefail` does not correctly identify failed nonlinear solver iterations, this would change the algorithm, so maybe it should be done in a separate PR), replace `SlowConvergence` with something more meaningful such as `MaxIters(Reached?)`, and perform some additional refactoring in derivative_utils.jl.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
what's the reason for moving all of the nlsolvers here? What's the plan for StochasticDiffEq?

**Comment by devmotion** [comment]
That's only a temporary solution since ultimately the nonlinear solver changes should be moved upstream to DiffEqBase. I think, it's unrealistic to assume that one will find the best design that covers all use cases of OrdinaryDiffEq and DelayDiffEq in just one single update, but iteratively changing the non-linear solvers in DiffEqBase will create a huge dependency mess and version jumps, even if the compatible versions are upper bounded. Worse, as I've already noticed in all the previous branches, tiny changes in DiffEqBase might have severe consequences in OrdinaryDiffEq or DelayDiffEq, which are difficult to spot and avoid if not both packages are tested and updated for each of these modifications. Hence I think it's much easier to come up with a good and reasonable setup and bugfixes by changing only OrdinaryDiffEq at the moment (also, IMO getting the support of DAEs right will be easier). If the design is stable, changes should be moved upstream.

**Comment by ChrisRackauckas** [comment]
That makes sense to me. Is there a nice way to keep StochasticDiffEq in sync? Maybe just have it depend on OrdinaryDiffEq is the true solution?

**Comment by devmotion** [comment]
Hmm.. I'm not sure. In principle, StochasticDiffEq should not have to depend on OrdinaryDiffEq since in contrast to, e.g., DelayDiffEq it does not make use of the ODE algorithms. Unfortunately currently there are many redundancies in OrdinaryDiffEq and StochasticDiffEq (e.g., initialization and derivative handling), with the latter usually being a bit outdated. IMO ideally there should be a common dependency for both OrdinaryDiffEq and StochasticDiffEq for these common functions and implementations, but I'm not sure if DiffEqBase is the right place for it.

**Comment by ChrisRackauckas** [comment]
I think it's fine to have the dependency in practice if we need to for now, but I hope StochasticDiffEq doesn't get super behind because then it's hard to update.

**Comment by devmotion** [comment]
Since the changes are supposed to be moved upstream as soon as the major bugs and inconsistencies in the implementation are fixed, each monitored by extensive benchmarking, and the design of the nonlinear solver captures all currently intended use cases, I'm not sure if it's worth adding a temporary dependency on OrdinaryDiffEq to StochasticDiffEq, in particular if the desired functionality has not stabilized yet.

**Comment by ChrisRackauckas** [comment]
Okay, sounds fine to me. Is this complete now, at least stage 1?

**Comment by devmotion** [comment]
Stage 1 👍
I noticed that additional simplifications in derivative_utils (without touching the algorithm) are possible by implementing a proper AbstractNLSolver for RadauIIA5, but as all the other improvements that can/should be part of additional PRs

**Comment by ChrisRackauckas** [comment]
@DiffEqBot runbenchmarks()

**Comment by ChrisRackauckas** [comment]
@DiffEqBot runbenchmarks

**Comment by ChrisRackauckas** [comment]
:(

**Comment by devmotion** [comment]
What does that mean? Is there an issue with DiffEqBot?

**Comment by ChrisRackauckas** [comment]
@kanav99 ?

**Comment by kanav99** [comment]
@DiffEqBot runbenchmarks

**Comment by kanav99** [comment]
Fine now. Dependency issue. Fixed it through an `admin` branch in Gitlab BenchmarkRepos. I would need a better dependency fix, I wasn't able to find actual reason why it happened. I got these CI issues lined up after my exams in coming week.

**Comment by ChrisRackauckas** [comment]
Regressions in TRBDF2 against https://github.com/DiffEqBot/Reports/blob/master/OrdinaryDiffEq.jl/769/f75fea5d1ee421859bec4c23432f00370c9cfd67/1561051063891.md

**Comment by devmotion** [comment]
Are there any more recent benchmarks? June 20 is quite old, and as I said, this PR is supposed to not change any algorithm and hence should not have any effect on the benchmarks.

**Comment by devmotion** [comment]
It seems the same regressions exist on master: https://github.com/DiffEqBot/Reports/blob/master/OrdinaryDiffEq.jl/921/5e32ba43fc30b5c16b360a7fa0a5277d5595705e/1567881158356.md

**Pull request merged**
