### PR TITLE
Bump DiffEqBase for tighter version bounds

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
Should fix GPU CI

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
https://gitlab.com/juliadiffeq/OrdinaryDiffEq-jl/-/jobs/354844763 I really don't get why this is considered a fail.

**Comment by devmotion** [comment]
Could it be due to https://gitlab.com/juliadiffeq/OrdinaryDiffEq-jl/-/jobs/354844763#L1471? It seems https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/d2d2dfef974c5e71e909e5be5e22adb4ec938ee8/.gitlab-ci.yml#L29
is never run?

**Comment by devmotion** [comment]
Yesterday it worked: https://gitlab.com/juliadiffeq/OrdinaryDiffEq-jl/-/jobs/354236320

**Comment by ChrisRackauckas** [comment]
@yingboma have you seen this?

**Comment by devmotion** [comment]
BTW 12 hours ago all tests passed (already using DiffEqBase 6.5): https://gitlab.com/juliadiffeq/OrdinaryDiffEq-jl/pipelines/96825218

**Comment by ChrisRackauckas** [comment]
Maybe that computer just needs to periodically restart? @YingboMa try restarting it and the tests today and see what happens. DiffEqBase, OrdinaryDiffEq, and DiffEqGPU are doing it. We may need to just put a Cron job on it to reset its cache?

**Comment by kanav99** [comment]
Can I have a look at the issue? I can run commands to test on the PC using a seperate branch (Like I used to do for the Bot)

**Comment by devmotion** [comment]
Tests pass on master, so the Gitlab issue seems to be fixed?

**Pull request merged**
