### PR TITLE
Test DiffEqBot

### PR DESCRIPTION
**Pull request by kanav99**
Hello @DiffEqBot

### CODE REVIEW

**Comment by kanav99** [comment]
@DiffEqBot runbenchmarks

**Comment by ChrisRackauckas** [comment]
Awesome work! Looks like `GC.gc()` calls should be added to make sure the GC doesn't run during timings.

**Comment by kanav99** [comment]
@DiffEqBot abort

**Comment by kanav99** [comment]
I wonder why DEStats fail now? Did something changed recently?

**Comment by ChrisRackauckas** [comment]
@YingboMa nonlinear solver change?

**Comment by kanav99** [comment]
I am opening this PR again for testing purposes.

**Comment by kanav99** [comment]
@DiffEqBot runbenchmarks

**Comment by kanav99** [comment]
@DiffEqBot runbenchmarks

**Comment by kanav99** [comment]
@DiffEqBot abort

**Comment by kanav99** [comment]
@DiffEqBot runbenchmarks

**Comment by kanav99** [comment]
@DiffEqBot runbenchmarks

**Comment by kanav99** [comment]
@DiffEqBot runbenchmarks

**Comment by ChrisRackauckas** [comment]
Can we set a minimum number of runs?

**Comment by kanav99** [comment]
By runs you mean number of samples for each benchmark? There are two parameters, max time and max samples, whichever exceeds first, the benchmarking is stopped.

**Comment by ChrisRackauckas** [comment]
Up the max time a bit. We should try to get a few samples in so that way this is more stable.

**Comment by kanav99** [comment]
@DiffEqBot runbenchmarks

**Comment by ChrisRackauckas** [comment]
Interesting... What about making it a minute?

**Comment by kanav99** [comment]
I don't understand these results at all.

**Comment by kanav99** [comment]
@DiffEqBot runbenchmarks

**Comment by kanav99** [comment]
Okay its still bad, maybe we should ask someone from JuliaCI about this?

**Comment by ChrisRackauckas** [comment]
For reference, make it 5 minutes?

Are we sure it's using our runner and not a shared runner?

**Comment by kanav99** [comment]
Making it 5 minutes will make it run for a couple of hours. Let's do it for one reference.

**Comment by kanav99** [comment]
@DiffEqBot runbenchmarks

**Comment by kanav99** [comment]
@DiffEqBot runbenchmarks

**Comment by kanav99** [comment]
@DiffEqBot runbenchmarks

**Comment by kanav99** [comment]
@DiffEqBot runbenchmarks

**Comment by kanav99** [comment]
Well I think it was all due to my computer, the bot is fine now. Last run was on my freshly restarted PC and the results are pretty accurate.

**Comment by ChrisRackauckas** [comment]
make it use the Gitlab runner now?

**Comment by kanav99** [comment]
Yeah we should. Setup the runner and I will message you the registration key.

**Comment by ChrisRackauckas** [comment]
Same runner as mentioned before. It's in the JuliaDiffEq project

**Comment by kanav99** [comment]
@DiffEqBot runbenchmarks

**Comment by kanav99** [comment]
@DiffEqBot runbenchmarks

**Comment by kanav99** [comment]
@DiffEqBot runbenchmarks

**Comment by ChrisRackauckas** [comment]
That one looks perfect.

**Comment by kanav99** [comment]
Yeah it does. We can maybe later reduce the time when it gets used more and more.

**Comment by ChrisRackauckas** [comment]
Well I think we can also just split the tests more, and just use different commands for different benchmark scripts.

**Comment by kanav99** [comment]
Yeah makes sense. I will open some issues on the DiffEqBenchmarkServer.jl so we don't forget all of this.

**Comment by ChrisRackauckas** [comment]
Also mention that in the next time things get updated, lets get StochasticDiffEq, DelayDiffEq, and DiffEqSensitivity setup with to be runnable. Also, DiffEqBase should get triggerable scripts for downstream steps.

**Pull request closed without merging**
