### PR TITLE
Update ExpRK alongside ExponentialUtilities

### PR DESCRIPTION
**Pull request by MSeeker1340**
Migrates exponential_utils.jl to an independent package ExponentialUtilities (https://github.com/JuliaDiffEq/ExponentialUtilities.jl). Also contains updates for EPIRK and convergence tests.

BTW @ChrisRackauckas how can I publish ExponentialUtilities to Julia's registry and set up the CI?

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Did you not generate the package via Pkg.generate? I don't see the CI ymls in there.

**Comment by ChrisRackauckas** [comment]
Registration is done via attobot. Just set a release. 

I think it's easiest to just `Pkg.generate` from v0.6 and copy the code over. However you get the ymls over is fine though.

**Comment by MSeeker1340** [comment]
> I think it's easiest to just Pkg.generate from v0.6 and copy the code over.

I'll give this a try, thanks!

**Comment by MSeeker1340** [comment]
Added autodiff support, mimicking what the implicit methods do.

**Comment by ChrisRackauckas** [comment]
The callbacks are fixed up so if you rebase then it should be done.

**Pull request merged**
