### PR TITLE
Add dense SSP output for `SSPRK22` and `SSPRK33`

### PR DESCRIPTION
**Pull request by ranocha**
This adds dense SSP output for the SSP methods `SSPRK22` and `SSPRK33` as described by Ketcheson, Lóczi, Jangabylova, Kusmanov: Dense output for SSP RK methods (2017).

See #39.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Is there a reason why you didn't add it to the 4th order method as well? Is the 3rd order Hermite a better idea than the 2nd order SSP interpolant? I know there is that order limit so that is the highest SSP there is. I'd pick whatever is useful for now, and then if it's really necessary add a type parameter in the algorithm constructor that can change it. But likely 4th order is just a bad idea for interpolation.

**Comment by ranocha** [comment]
In section 4.4, Ketcheson et al. do not mention SSPRK(10,4). The reason may be that the resulting dense SSP output has a stricter restriction on the time step than the base method. They don't mention this explicitly but I will have a look at it.
If this is correct, we can as well have a higher order Hermite interpolation, since the dense 'SSP' output won't be SSP either.

**Comment by ranocha** [comment]
`SSPRK104` does not fulfil any of the conditions of Theorem 5 of Ketcheson et al. In section 4.4, they mention that they have not been able to construct dense SSP output with SSP coefficients as large as the base method. Thus, it would require deeper investigations or may be impossible to find an acceptable 2nd order SSP dense output for `SSPRK104`.

**Comment by ChrisRackauckas** [comment]
Thanks for the overview. It's good to have it documented. I have started to contact Ketcheson to see if there's stuff about this, along with error estimators for adaptivity. We'll see how it that goes.

**Pull request merged**
